In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('./play_tennis.csv')

In [6]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [8]:
yp=9/14
yn=5/14
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [10]:
nover=0
nrain=2/5
nsunny=3/5

yover=4/9
yrain=3/9
ysunny=2/9
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [12]:
ncool=1/5
nhot=2/5
nmild=2/5

ycool=3/9
yhot=2/9
ymild=4/9
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [16]:
yhigh=3/9
ynormal=6/9

nhigh=4/5
nnormal=1/5
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [17]:
nstrong=3/5
nweak=2/5

ystrong=3/9
yweak=6/9

In [20]:
# for sunny,mild,weak
ypred=yp*ysunny*ymild*yweak
print(ypred)

0.042328042328042326

In [21]:
npred=yn*nsunny*nmild*nweak
print(npred)

0.03428571428571429

### As we can see the prediction of Yes play (ypred) is more than No play (npred) so the match will be played